# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.10/ubuntu-14.10-amd64.box"

  config.omnibus.chef_version = :latest

  config.vm.define :master do |master|
    master.vm.network :forwarded_port, guest: 80, host: 8081
    master.vm.network :private_network, ip: "192.168.0.10", virtualbox__intnet: "intnet"

    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end

    master.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = ["./cookbooks/","./site-cookbooks/"]
      chef.add_recipe "java"
      chef.json = {
        java: {
          install_flavor: "oracle",
          jdk_version: "8",
          oracle: {
            accept_oracle_download_terms: true
          },
        }
      }
    end
  end
end
